"""
Type stubs for aspose.pydrawing
Auto-generated from runtime introspection.
"""
from typing import Any, ClassVar, Optional, List, Tuple, Union, overload

from . import design
from . import drawing2d
from . import imaging
from . import printing
from . import text

class Bitmap:
    '''System.Drawing.Bitmap wrapper.'''
    
    # Properties
    @property
    def flags(self) -> Any: ...
    @property
    def frame_dimensions_list(self) -> Any: ...
    @property
    def height(self) -> Any: ...
    @property
    def horizontal_resolution(self) -> Any: ...
    @property
    def palette(self) -> Any: ...
    @property
    def physical_dimension(self) -> Any: ...
    @property
    def pixel_format(self) -> Any: ...
    @property
    def property_id_list(self) -> Any: ...
    @property
    def property_items(self) -> Any: ...
    @property
    def raw_format(self) -> Any: ...
    @property
    def size(self) -> Any: ...
    @property
    def tag(self) -> Any: ...
    @property
    def vertical_resolution(self) -> Any: ...
    @property
    def width(self) -> Any: ...
    
    # Methods
    def clone(self, *args) -> Any: ...
    def from_file(self, *args) -> Any: ...
    def from_stream(self, *args) -> Any: ...
    def get_bounds(self, *args) -> Any: ...
    def get_encoder_parameter_list(self, *args) -> Any: ...
    def get_frame_count(self, *args) -> Any: ...
    def get_pixel(self, *args) -> Any: ...
    def get_pixel_format_size(self, *args) -> Any: ...
    def get_property_item(self, *args) -> Any: ...
    def get_type(self, *args) -> Any: ...
    def is_alpha_pixel_format(self, *args) -> Any: ...
    def is_canonical_pixel_format(self, *args) -> Any: ...
    def is_extended_pixel_format(self, *args) -> Any: ...
    def lock_bits(self, *args) -> Any: ...
    def make_transparent(self, *args) -> Any: ...
    def remove_property_item(self, *args) -> Any: ...
    def rotate_flip(self, *args) -> Any: ...
    def save(self, *args) -> Any: ...
    def save_add(self, *args) -> Any: ...
    def select_active_frame(self, *args) -> Any: ...
    def set_pixel(self, *args) -> Any: ...
    def set_property_item(self, *args) -> Any: ...
    def set_resolution(self, *args) -> Any: ...
    def unlock_bits(self, *args) -> Any: ...

class BitmapSuffixInSameAssemblyAttribute:
    '''Wrapper for System.Drawing.BitmapSuffixInSameAssemblyAttribute'''
    def __init__(self, *args, **kwargs) -> None: ...

class BitmapSuffixInSatelliteAssemblyAttribute:
    '''Wrapper for System.Drawing.BitmapSuffixInSatelliteAssemblyAttribute'''
    def __init__(self, *args, **kwargs) -> None: ...

class Brush:
    '''System.Drawing.Brush wrapper.'''
    
    # Methods
    def clone(self, *args) -> Any: ...
    def get_type(self, *args) -> Any: ...

class Brushes:
    '''Wrapper for System.Drawing.Brushes'''
    def __init__(self, *args, **kwargs) -> None: ...

class BufferedGraphics:
    '''Wrapper for System.Drawing.BufferedGraphics'''
    def __init__(self, *args, **kwargs) -> None: ...

class BufferedGraphicsContext:
    '''Wrapper for System.Drawing.BufferedGraphicsContext'''
    def __init__(self, *args, **kwargs) -> None: ...

class BufferedGraphicsManager:
    '''Wrapper for System.Drawing.BufferedGraphicsManager'''
    def __init__(self, *args, **kwargs) -> None: ...

class CharacterRange:
    '''Wrapper for System.Drawing.CharacterRange'''
    def __init__(self, *args, **kwargs) -> None: ...

class Color:
    '''System.Drawing.Color wrapper.'''
    
    # Named values
    alice_blue: ClassVar[Color]
    antique_white: ClassVar[Color]
    aqua: ClassVar[Color]
    aquamarine: ClassVar[Color]
    azure: ClassVar[Color]
    beige: ClassVar[Color]
    bisque: ClassVar[Color]
    black: ClassVar[Color]
    blanched_almond: ClassVar[Color]
    blue: ClassVar[Color]
    blue_violet: ClassVar[Color]
    brown: ClassVar[Color]
    burly_wood: ClassVar[Color]
    cadet_blue: ClassVar[Color]
    chartreuse: ClassVar[Color]
    chocolate: ClassVar[Color]
    coral: ClassVar[Color]
    cornflower_blue: ClassVar[Color]
    cornsilk: ClassVar[Color]
    crimson: ClassVar[Color]
    cyan: ClassVar[Color]
    dark_blue: ClassVar[Color]
    dark_cyan: ClassVar[Color]
    dark_goldenrod: ClassVar[Color]
    dark_gray: ClassVar[Color]
    dark_green: ClassVar[Color]
    dark_khaki: ClassVar[Color]
    dark_magenta: ClassVar[Color]
    dark_olive_green: ClassVar[Color]
    dark_orange: ClassVar[Color]
    dark_orchid: ClassVar[Color]
    dark_red: ClassVar[Color]
    dark_salmon: ClassVar[Color]
    dark_sea_green: ClassVar[Color]
    dark_slate_blue: ClassVar[Color]
    dark_slate_gray: ClassVar[Color]
    dark_turquoise: ClassVar[Color]
    dark_violet: ClassVar[Color]
    deep_pink: ClassVar[Color]
    deep_sky_blue: ClassVar[Color]
    dim_gray: ClassVar[Color]
    dodger_blue: ClassVar[Color]
    firebrick: ClassVar[Color]
    floral_white: ClassVar[Color]
    forest_green: ClassVar[Color]
    fuchsia: ClassVar[Color]
    gainsboro: ClassVar[Color]
    ghost_white: ClassVar[Color]
    gold: ClassVar[Color]
    goldenrod: ClassVar[Color]
    gray: ClassVar[Color]
    green: ClassVar[Color]
    green_yellow: ClassVar[Color]
    honeydew: ClassVar[Color]
    hot_pink: ClassVar[Color]
    indian_red: ClassVar[Color]
    indigo: ClassVar[Color]
    ivory: ClassVar[Color]
    khaki: ClassVar[Color]
    lavender: ClassVar[Color]
    lavender_blush: ClassVar[Color]
    lawn_green: ClassVar[Color]
    lemon_chiffon: ClassVar[Color]
    light_blue: ClassVar[Color]
    light_coral: ClassVar[Color]
    light_cyan: ClassVar[Color]
    light_goldenrod_yellow: ClassVar[Color]
    light_gray: ClassVar[Color]
    light_green: ClassVar[Color]
    light_pink: ClassVar[Color]
    light_salmon: ClassVar[Color]
    light_sea_green: ClassVar[Color]
    light_sky_blue: ClassVar[Color]
    light_slate_gray: ClassVar[Color]
    light_steel_blue: ClassVar[Color]
    light_yellow: ClassVar[Color]
    lime: ClassVar[Color]
    lime_green: ClassVar[Color]
    linen: ClassVar[Color]
    magenta: ClassVar[Color]
    maroon: ClassVar[Color]
    medium_aquamarine: ClassVar[Color]
    medium_blue: ClassVar[Color]
    medium_orchid: ClassVar[Color]
    medium_purple: ClassVar[Color]
    medium_sea_green: ClassVar[Color]
    medium_slate_blue: ClassVar[Color]
    medium_spring_green: ClassVar[Color]
    medium_turquoise: ClassVar[Color]
    medium_violet_red: ClassVar[Color]
    midnight_blue: ClassVar[Color]
    mint_cream: ClassVar[Color]
    misty_rose: ClassVar[Color]
    moccasin: ClassVar[Color]
    navajo_white: ClassVar[Color]
    navy: ClassVar[Color]
    old_lace: ClassVar[Color]
    olive: ClassVar[Color]
    olive_drab: ClassVar[Color]
    orange: ClassVar[Color]
    orange_red: ClassVar[Color]
    orchid: ClassVar[Color]
    pale_goldenrod: ClassVar[Color]
    pale_green: ClassVar[Color]
    pale_turquoise: ClassVar[Color]
    pale_violet_red: ClassVar[Color]
    papaya_whip: ClassVar[Color]
    peach_puff: ClassVar[Color]
    peru: ClassVar[Color]
    pink: ClassVar[Color]
    plum: ClassVar[Color]
    powder_blue: ClassVar[Color]
    purple: ClassVar[Color]
    rebecca_purple: ClassVar[Color]
    red: ClassVar[Color]
    rosy_brown: ClassVar[Color]
    royal_blue: ClassVar[Color]
    saddle_brown: ClassVar[Color]
    salmon: ClassVar[Color]
    sandy_brown: ClassVar[Color]
    sea_green: ClassVar[Color]
    sea_shell: ClassVar[Color]
    sienna: ClassVar[Color]
    silver: ClassVar[Color]
    sky_blue: ClassVar[Color]
    slate_blue: ClassVar[Color]
    slate_gray: ClassVar[Color]
    snow: ClassVar[Color]
    spring_green: ClassVar[Color]
    steel_blue: ClassVar[Color]
    tan: ClassVar[Color]
    teal: ClassVar[Color]
    thistle: ClassVar[Color]
    tomato: ClassVar[Color]
    transparent: ClassVar[Color]
    turquoise: ClassVar[Color]
    violet: ClassVar[Color]
    wheat: ClassVar[Color]
    white: ClassVar[Color]
    white_smoke: ClassVar[Color]
    yellow: ClassVar[Color]
    yellow_green: ClassVar[Color]
    
    # Properties
    @property
    def a(self) -> Any: ...
    @property
    def b(self) -> Any: ...
    @property
    def g(self) -> Any: ...
    @property
    def is_empty(self) -> Any: ...
    @property
    def is_known_color(self) -> Any: ...
    @property
    def is_named_color(self) -> Any: ...
    @property
    def is_system_color(self) -> Any: ...
    @property
    def name(self) -> Any: ...
    @property
    def r(self) -> Any: ...
    
    # Methods
    def empty(self, *args) -> Any: ...
    @staticmethod
    def from_argb(*args) -> Color: ...
    @staticmethod
    def from_known_color(*args) -> Color: ...
    @staticmethod
    def from_name(*args) -> Color: ...
    def get_brightness(self, *args) -> Any: ...
    def get_hue(self, *args) -> Any: ...
    def get_saturation(self, *args) -> Any: ...
    def get_type(self, *args) -> Any: ...
    def to_argb(self, *args) -> Any: ...
    def to_known_color(self, *args) -> Any: ...

class ColorTranslator:
    '''Wrapper for System.Drawing.ColorTranslator'''
    def __init__(self, *args, **kwargs) -> None: ...

class ContentAlignment:
    '''Wrapper for System.Drawing.ContentAlignment'''
    def __init__(self, *args, **kwargs) -> None: ...

class CopyPixelOperation:
    '''Wrapper for System.Drawing.CopyPixelOperation'''
    def __init__(self, *args, **kwargs) -> None: ...

class Font:
    '''System.Drawing.Font wrapper.'''
    
    # Properties
    @property
    def bold(self) -> Any: ...
    @property
    def font_family(self) -> Any: ...
    @property
    def gdi_char_set(self) -> Any: ...
    @property
    def gdi_vertical_font(self) -> Any: ...
    @property
    def height(self) -> Any: ...
    @property
    def is_system_font(self) -> Any: ...
    @property
    def italic(self) -> Any: ...
    @property
    def name(self) -> Any: ...
    @property
    def original_font_name(self) -> Any: ...
    @property
    def size(self) -> Any: ...
    @property
    def size_in_points(self) -> Any: ...
    @property
    def strikeout(self) -> Any: ...
    @property
    def style(self) -> Any: ...
    @property
    def system_font_name(self) -> Any: ...
    @property
    def underline(self) -> Any: ...
    @property
    def unit(self) -> Any: ...
    
    # Methods
    def clone(self, *args) -> Any: ...
    def from_log_font(self, *args) -> Any: ...
    def get_height(self, *args) -> Any: ...
    def get_type(self, *args) -> Any: ...
    def to_log_font(self, *args) -> Any: ...

class FontConverter:
    '''Wrapper for System.Drawing.FontConverter'''
    def __init__(self, *args, **kwargs) -> None: ...

class FontFamily:
    '''Wrapper for System.Drawing.FontFamily'''
    def __init__(self, *args, **kwargs) -> None: ...

class FontStyle:
    '''Wrapper for System.Drawing.FontStyle'''
    def __init__(self, *args, **kwargs) -> None: ...

class Graphics:
    '''System.Drawing.Graphics wrapper.'''
    
    # Properties
    @property
    def clip(self) -> Any: ...
    @property
    def clip_bounds(self) -> Any: ...
    @property
    def compositing_mode(self) -> Any: ...
    @property
    def compositing_quality(self) -> Any: ...
    @property
    def dpi_x(self) -> Any: ...
    @property
    def dpi_y(self) -> Any: ...
    @property
    def interpolation_mode(self) -> Any: ...
    @property
    def is_clip_empty(self) -> Any: ...
    @property
    def is_visible_clip_empty(self) -> Any: ...
    @property
    def page_scale(self) -> Any: ...
    @property
    def page_unit(self) -> Any: ...
    @property
    def pixel_offset_mode(self) -> Any: ...
    @property
    def rendering_origin(self) -> Any: ...
    @property
    def smoothing_mode(self) -> Any: ...
    @property
    def text_contrast(self) -> Any: ...
    @property
    def text_rendering_hint(self) -> Any: ...
    @property
    def transform(self) -> Any: ...
    @property
    def visible_clip_bounds(self) -> Any: ...
    
    # Methods
    def add_metafile_comment(self, *args) -> Any: ...
    def begin_container(self, *args) -> Any: ...
    def clear(self, *args) -> Any: ...
    def copy_from_screen(self, *args) -> Any: ...
    def draw_arc(self, *args) -> Any: ...
    def draw_bezier(self, *args) -> Any: ...
    def draw_beziers(self, *args) -> Any: ...
    def draw_closed_curve(self, *args) -> Any: ...
    def draw_curve(self, *args) -> Any: ...
    def draw_ellipse(self, *args) -> Any: ...
    def draw_icon(self, *args) -> Any: ...
    def draw_icon_unstretched(self, *args) -> Any: ...
    def draw_image(self, *args) -> Any: ...
    def draw_image_unscaled(self, *args) -> Any: ...
    def draw_image_unscaled_and_clipped(self, *args) -> Any: ...
    def draw_line(self, *args) -> Any: ...
    def draw_lines(self, *args) -> Any: ...
    def draw_path(self, *args) -> Any: ...
    def draw_pie(self, *args) -> Any: ...
    def draw_polygon(self, *args) -> Any: ...
    def draw_rectangle(self, *args) -> Any: ...
    def draw_rectangles(self, *args) -> Any: ...
    def draw_string(self, *args) -> Any: ...
    def end_container(self, *args) -> Any: ...
    def exclude_clip(self, *args) -> Any: ...
    def fill_closed_curve(self, *args) -> Any: ...
    def fill_ellipse(self, *args) -> Any: ...
    def fill_path(self, *args) -> Any: ...
    def fill_pie(self, *args) -> Any: ...
    def fill_polygon(self, *args) -> Any: ...
    def fill_rectangle(self, *args) -> Any: ...
    def fill_rectangles(self, *args) -> Any: ...
    def fill_region(self, *args) -> Any: ...
    def flush(self, *args) -> Any: ...
    def from_image(self, *args) -> Any: ...
    def get_context_info(self, *args) -> Any: ...
    def get_nearest_color(self, *args) -> Any: ...
    def get_type(self, *args) -> Any: ...
    def intersect_clip(self, *args) -> Any: ...
    def is_visible(self, *args) -> Any: ...
    def measure_character_ranges(self, *args) -> Any: ...
    def measure_string(self, *args) -> Any: ...
    def multiply_transform(self, *args) -> Any: ...
    def release_hdc(self, *args) -> Any: ...
    def reset_clip(self, *args) -> Any: ...
    def reset_transform(self, *args) -> Any: ...
    def restore(self, *args) -> Any: ...
    def rotate_transform(self, *args) -> Any: ...
    def save(self, *args) -> Any: ...
    def scale_transform(self, *args) -> Any: ...
    def set_clip(self, *args) -> Any: ...
    def transform_points(self, *args) -> Any: ...
    def translate_clip(self, *args) -> Any: ...
    def translate_transform(self, *args) -> Any: ...

class GraphicsUnit:
    '''Wrapper for System.Drawing.GraphicsUnit'''
    def __init__(self, *args, **kwargs) -> None: ...

class IDeviceContext:
    '''Wrapper for System.Drawing.IDeviceContext'''
    def __init__(self, *args, **kwargs) -> None: ...

class Icon:
    '''Wrapper for System.Drawing.Icon'''
    def __init__(self, *args, **kwargs) -> None: ...

class IconConverter:
    '''Wrapper for System.Drawing.IconConverter'''
    def __init__(self, *args, **kwargs) -> None: ...

class Image:
    '''System.Drawing.Image wrapper.'''
    
    # Properties
    @property
    def flags(self) -> Any: ...
    @property
    def frame_dimensions_list(self) -> Any: ...
    @property
    def height(self) -> Any: ...
    @property
    def horizontal_resolution(self) -> Any: ...
    @property
    def palette(self) -> Any: ...
    @property
    def physical_dimension(self) -> Any: ...
    @property
    def pixel_format(self) -> Any: ...
    @property
    def property_id_list(self) -> Any: ...
    @property
    def property_items(self) -> Any: ...
    @property
    def raw_format(self) -> Any: ...
    @property
    def size(self) -> Any: ...
    @property
    def tag(self) -> Any: ...
    @property
    def vertical_resolution(self) -> Any: ...
    @property
    def width(self) -> Any: ...
    
    # Methods
    def clone(self, *args) -> Any: ...
    def from_file(self, *args) -> Any: ...
    def from_stream(self, *args) -> Any: ...
    def get_bounds(self, *args) -> Any: ...
    def get_encoder_parameter_list(self, *args) -> Any: ...
    def get_frame_count(self, *args) -> Any: ...
    def get_pixel_format_size(self, *args) -> Any: ...
    def get_property_item(self, *args) -> Any: ...
    def get_type(self, *args) -> Any: ...
    def is_alpha_pixel_format(self, *args) -> Any: ...
    def is_canonical_pixel_format(self, *args) -> Any: ...
    def is_extended_pixel_format(self, *args) -> Any: ...
    def remove_property_item(self, *args) -> Any: ...
    def rotate_flip(self, *args) -> Any: ...
    def save(self, *args) -> Any: ...
    def save_add(self, *args) -> Any: ...
    def select_active_frame(self, *args) -> Any: ...
    def set_property_item(self, *args) -> Any: ...

class ImageAnimator:
    '''Wrapper for System.Drawing.ImageAnimator'''
    def __init__(self, *args, **kwargs) -> None: ...

class ImageConverter:
    '''Wrapper for System.Drawing.ImageConverter'''
    def __init__(self, *args, **kwargs) -> None: ...

class ImageFormatConverter:
    '''Wrapper for System.Drawing.ImageFormatConverter'''
    def __init__(self, *args, **kwargs) -> None: ...

class KnownColor:
    '''Wrapper for System.Drawing.KnownColor'''
    def __init__(self, *args, **kwargs) -> None: ...

class Pen:
    '''System.Drawing.Pen wrapper.'''
    
    # Properties
    @property
    def alignment(self) -> Any: ...
    @property
    def brush(self) -> Any: ...
    @property
    def color(self) -> Any: ...
    @property
    def compound_array(self) -> Any: ...
    @property
    def custom_end_cap(self) -> Any: ...
    @property
    def custom_start_cap(self) -> Any: ...
    @property
    def dash_cap(self) -> Any: ...
    @property
    def dash_offset(self) -> Any: ...
    @property
    def dash_pattern(self) -> Any: ...
    @property
    def dash_style(self) -> Any: ...
    @property
    def end_cap(self) -> Any: ...
    @property
    def line_join(self) -> Any: ...
    @property
    def miter_limit(self) -> Any: ...
    @property
    def pen_type(self) -> Any: ...
    @property
    def start_cap(self) -> Any: ...
    @property
    def transform(self) -> Any: ...
    @property
    def width(self) -> Any: ...
    
    # Methods
    def clone(self, *args) -> Any: ...
    def get_type(self, *args) -> Any: ...
    def multiply_transform(self, *args) -> Any: ...
    def reset_transform(self, *args) -> Any: ...
    def rotate_transform(self, *args) -> Any: ...
    def scale_transform(self, *args) -> Any: ...
    def set_line_cap(self, *args) -> Any: ...
    def translate_transform(self, *args) -> Any: ...

class Pens:
    '''Wrapper for System.Drawing.Pens'''
    def __init__(self, *args, **kwargs) -> None: ...

class Point:
    '''System.Drawing.Point wrapper.'''
    
    # Properties
    @property
    def is_empty(self) -> Any: ...
    @property
    def x(self) -> Any: ...
    @property
    def y(self) -> Any: ...
    
    # Methods
    def add(self, *args) -> Any: ...
    def ceiling(self, *args) -> Any: ...
    def empty(self, *args) -> Any: ...
    def get_type(self, *args) -> Any: ...
    def offset(self, *args) -> Any: ...
    def round(self, *args) -> Any: ...
    def subtract(self, *args) -> Any: ...
    def truncate(self, *args) -> Any: ...

class PointF:
    '''System.Drawing.PointF wrapper.'''
    
    # Properties
    @property
    def is_empty(self) -> Any: ...
    @property
    def x(self) -> Any: ...
    @property
    def y(self) -> Any: ...
    
    # Methods
    def add(self, *args) -> Any: ...
    def empty(self, *args) -> Any: ...
    def get_type(self, *args) -> Any: ...
    def subtract(self, *args) -> Any: ...

class Rectangle:
    '''Wrapper for System.Drawing.Rectangle'''
    def __init__(self, *args, **kwargs) -> None: ...

class RectangleF:
    '''Wrapper for System.Drawing.RectangleF'''
    def __init__(self, *args, **kwargs) -> None: ...

class Region:
    '''Wrapper for System.Drawing.Region'''
    def __init__(self, *args, **kwargs) -> None: ...

class RotateFlipType:
    '''Wrapper for System.Drawing.RotateFlipType'''
    def __init__(self, *args, **kwargs) -> None: ...

class Size:
    '''System.Drawing.Size wrapper.'''
    
    # Properties
    @property
    def height(self) -> Any: ...
    @property
    def is_empty(self) -> Any: ...
    @property
    def width(self) -> Any: ...
    
    # Methods
    def add(self, *args) -> Any: ...
    def ceiling(self, *args) -> Any: ...
    def empty(self, *args) -> Any: ...
    def get_type(self, *args) -> Any: ...
    def round(self, *args) -> Any: ...
    def subtract(self, *args) -> Any: ...
    def truncate(self, *args) -> Any: ...

class SizeF:
    '''System.Drawing.SizeF wrapper.'''
    
    # Properties
    @property
    def height(self) -> Any: ...
    @property
    def is_empty(self) -> Any: ...
    @property
    def width(self) -> Any: ...
    
    # Methods
    def add(self, *args) -> Any: ...
    def empty(self, *args) -> Any: ...
    def get_type(self, *args) -> Any: ...
    def subtract(self, *args) -> Any: ...
    def to_point_f(self, *args) -> Any: ...
    def to_size(self, *args) -> Any: ...

class SolidBrush:
    '''System.Drawing.SolidBrush wrapper.'''
    
    # Properties
    @property
    def color(self) -> Any: ...
    
    # Methods
    def clone(self, *args) -> Any: ...
    def get_type(self, *args) -> Any: ...

class StringAlignment:
    '''Wrapper for System.Drawing.StringAlignment'''
    def __init__(self, *args, **kwargs) -> None: ...

class StringDigitSubstitute:
    '''Wrapper for System.Drawing.StringDigitSubstitute'''
    def __init__(self, *args, **kwargs) -> None: ...

class StringFormat:
    '''Wrapper for System.Drawing.StringFormat'''
    def __init__(self, *args, **kwargs) -> None: ...

class StringFormatFlags:
    '''Wrapper for System.Drawing.StringFormatFlags'''
    def __init__(self, *args, **kwargs) -> None: ...

class StringTrimming:
    '''Wrapper for System.Drawing.StringTrimming'''
    def __init__(self, *args, **kwargs) -> None: ...

class StringUnit:
    '''Wrapper for System.Drawing.StringUnit'''
    def __init__(self, *args, **kwargs) -> None: ...

class SystemBrushes:
    '''Wrapper for System.Drawing.SystemBrushes'''
    def __init__(self, *args, **kwargs) -> None: ...

class SystemColors:
    '''Wrapper for System.Drawing.SystemColors'''
    def __init__(self, *args, **kwargs) -> None: ...

class SystemFonts:
    '''Wrapper for System.Drawing.SystemFonts'''
    def __init__(self, *args, **kwargs) -> None: ...

class SystemIcons:
    '''Wrapper for System.Drawing.SystemIcons'''
    def __init__(self, *args, **kwargs) -> None: ...

class SystemPens:
    '''Wrapper for System.Drawing.SystemPens'''
    def __init__(self, *args, **kwargs) -> None: ...

class TextureBrush:
    '''Wrapper for System.Drawing.TextureBrush'''
    def __init__(self, *args, **kwargs) -> None: ...

class ToolboxBitmapAttribute:
    '''Wrapper for System.Drawing.ToolboxBitmapAttribute'''
    def __init__(self, *args, **kwargs) -> None: ...
